### ISSUE TITLE
Help in parameters

### ISSUE THREAD

**Issue by SND8041** [opcode81/ProbCog#11]
Hello, 
I am trying to use "[soft evidence] error with independent soft evidence and weighting of worlds" in the MLN Parameter Learning Tools, but getting the error "... Exception: Mode LL_ISEWW: gradient function is not implemented". It seems that I am missing the parameters in the "Add. Params" box. Is there any wiki or help regarding the learning methods and their parameters?

Syed

**Comment by opcode81** [comment]
This has now fixed with commit f98b537. Please pull the new changes.
