### ISSUE TITLE
Alchemy (Win32 desktop)?

### ISSUE THREAD

**Issue by SND8041** [opcode81/ProbCog#12]
I wonder how would I use any of the engines starting with the title "Alchemy" for example Alchemy (win32 desktop) or Alchemy (Win32 laptop) in mlnquery?
Also what is their purpose? What algorithms are used in PyMLNs and J-MLNs? Is this sufficient to use PyMLN instead of using other engines like Alchemy (Win32 ...), I mean I am confused as I don't know what are the differences in all these engines, after all we already have different inference methods such as MC-SAT, or Gibbs sampling.

I hope you understand.

Syed

**Comment by opcode81** [comment]
You would use them by (1) installing Alchemy, a learning and inference engine developed by members of the University of Washington and (2) configuring the path under which it is installed by editing the file `src/main/python/configMLN.py`.
The purpose is to provide access to (a) additional algorithms and (b) alternative implementations of the same algorithms with different properties (regarding, for example, parametrisation and runtime behaviour).
If you don't know why you would need another engine, you probably don't need one.

**Comment by SND8041** [comment]
This really helped me. One thing more, Is Alchemy available for only Linux/Ubunto or it is also available for  Windows?

**Comment by SND8041** [comment]
This really helped me. One thing more, Is Alchemy available for only Linux/Ubunto or it is also available for Windows?

**Comment by opcode81** [comment]
It don't know if anyone's currently offering precompiled binaries for Windows that you could just use, but it's possible to compile it yourself under CygWin, which is what I always used to do.

**Comment by SND8041** [comment]
Thank you very much for help!

 

Best regards,

Syed

**Comment by opcode81** [comment]
These days, Windows 10's subsystem for Linux should work as well. Probably easier than CygWin, I'd say.

**Comment by SND8041** [comment]
I am going to try Windows 10’s subsystem for Linux. Thank you for your valuable help.
