### ISSUE TITLE
difference in results over two different machines!

### ISSUE THREAD

**Issue by SND8041** [opcode81/ProbCog#13]
Hi,
I am using MLN as a technique in my research work. I have developed an MLN model for which I have a .mln file containing the formulas, predicates, and type definitions. I also have training data in a file. I am using mlnlearn to learn the weights of the formulas. It is purely by luck that I used two different machines, both from Dell (one is the desktop and the other is a laptop Dell Precision M6500). On my desktop Windows 10 Enterprise is installed and on my laptop Windows 10 Prof is installed. To my surprise, by using the same input files and parameters (prior with 100 std. dev.) and same algorithm (pseudo-log-likelihood) and using the same engine (internal) the results on these machines are remarkably different! Do you know what might be causing this? Which one will be more accurate?

Syed

**Comment by opcode81** [comment]
Could you please provide a few more details? What exactly do your different results look like?
It's quite possible that your MLN has infinitely many optimal solutions (plateau). Do inference results you get with these networks vary widely?

**Comment by opcode81** [comment]
Closing issue as no further details were provided.
