### ISSUE TITLE
ROS package

### ISSUE THREAD

**Issue by AnujGandhi123** [opcode81/ProbCog#16]
Does your ROS service only work on inference and not learning?
And i was able to configure Alchemy on your interface using the thread - issue #12 
However, Can I do the same on ROS?

**Comment by opcode81** [comment]
The ROS package is for inference only.
Note that I no longer maintain the ROS package; it has not been touched in ~7 years.
It would be straightforward to add additional features already supported by ProbCog itself to the ROS package, but I will not engage in future development of the package.

**Comment by AnujGandhi123** [comment]
Okay Thanks. I have one question before I look at the code.  Does it support Alchemy Syntax for mln?

**Comment by opcode81** [comment]
It supports whatever ProbCog supports, it's just a small package that provides inference functionality as a ROS service.
