### ISSUE TITLE
Problem related to ConfigurePOM.PY

### ISSUE THREAD

**Issue by anjumm** [opcode81/ProbCog#20]
Dear ProbCog Team,

Hi. Hope you are doing well.

I am trying to install ProbCog but facing this issue.

 File "C:\Users\Anjum Malik\Desktop\ProbCog-master\configurePOM.py", line 27
    print "Failed to detect architecture. Please provide one of the following as an argument:\n    %s" % ", ".join(archs)

Can you try to help me related with this. Awaiting your response. 

Regards,

Anjum

**Comment by opcode81** [comment]
Dear Anjum, please provide the full stack trace.
Just to make sure, are you using Python 2.7?
If so, which platform/OS are you on?

**Comment by tpacker** [comment]
FWIF, I had the same problem on Mac and got past it by simply hard-coding my platform string in the python script.

**Comment by hiraad** [comment]
this worked for me, just had to downgrade my python to 2.7 . thanks for the quick reply.
