### ISSUE TITLE
BLN Query Tool

### ISSUE THREAD

**Issue by anjumm** [opcode81/ProbCog#21]
Hi. Hope you are doing well. I am trying to work on BLN query tool. I can access the network editor but I am unable to upload grades-ext files(example folder) in Query tool. Tool is giving option only for default xml files which I am unable to locate. Your help will be appreciated in this regard. 

PFA picture of query tool as well. 
![BLN](https://user-images.githubusercontent.com/47303481/57714572-19f13480-7675-11e9-8582-1d76b2707440.png)

Anjum

**Comment by opcode81** [comment]
Which files are you trying to load that you don't find in the list?

**Comment by anjumm** [comment]
Yes I am trying to open grades_tutorial.learnt.xml file. It opens the network editor from fragment section and I can visualize it.  But when the network editor is open I am unable to access BLN query tool. I am trying to check the inference based on this link. 

https://github.com/opcode81/ProbCog/wiki/BLN-Query-Tool

**Comment by opcode81** [comment]
Your description of the problem is rather confusing. Please state precisely what your problem is.

Things to bear in mind: You must run blnquery from the directory where the files you want to work with are located. Then you will find them in the dropdown lists.

**Comment by opcode81** [comment]
Is your problem solved?
