### ISSUE TITLE
basic question

### ISSUE THREAD

**Issue by AnujGandhi123** [opcode81/ProbCog#22]
I'm trying to find the difference between BLOG and BLN framework. Looks like you build on top of BLOG and are using BLOG specific syntaxes at some places. Can you help highlight the differences?

I'm not as familiar with BLOG but I've read the paper on BLN.

**Comment by opcode81** [comment]
The BLN language uses BLOG-like syntax for a few aspects, and early versions of the language were essentially a subset of BLOG, but the languages then diverged. BLNs do not have a notion of unknown objects, for example. Instead, they are built on the same template semantics as MLNs, for example, with the principle of shallow transfer being at the heart of their semantics. BLNs add a convenient logical reasoning layer for evidence predicates (via Prolog) and, most crucially, add a notion of hard logical constraints that can be modelled outside the Bayesian network template semantics. Therefore, a most fitting view of BLNs is to regard them as relational template models for mixed networks (which integrate Bayesian networks with constraint networks).

**Comment by AnujGandhi123** [comment]
That's what I thought as well. Thank You.
I have got a few more questions.
1.) In your paper for BLN, you describe future scope as adding soft logical constraints like those in MLN, did you end up adding it or/and is there a paper available on it?
2.) Did the software have support for Hybrid (Continuous) Domains?
3.) As you use Bayesian Network, apart from the directionality constraints due to directed edges and not being able to model cyclic relations, does it share most of the cons of the Bayesian network? Or have I got it wrong?

**Comment by opcode81** [comment]
1) No, it didn't seem like a worthwhile endeavour in the end.
2) No.
3) It is a misconception that the acyclic nature of Bayesian networks has anything to do with the relations that can be modelled. In particular, given a set of discrete variables, a Bayesian network can be used to model any probability distribution over these variables. 
It's unclear which cons you are referring to. This is largely a subjective and context-specific question. For instance, what is perceived as a drawback from a modelling perspective can be a computational advantage.
To me, the most relevant disadvantage from a modelling perspective is the way in which the distribution is required to factorise. In a Markov random field, local relationships can be arbitrarily added as desired, as there is no requirement for factors to be (conditional) distributions. BLNs alleviate the limitation to some degree, as they allow hard constraints to be added freely. The addition of soft constraints could have further advanced that freedom, yet it would likely have defeated the purpose of the directed representation.
