### ISSUE TITLE
Why can't I use PyMLNs engine in mlnlearn tool？

### ISSUE THREAD

**Issue by MRSHIMMER** [opcode81/ProbCog#29]
I try to follow this tutorial (https://github.com/opcode81/ProbCog/wiki/MLN-Tutorial). However, when using the mlnlearn tool, I can't use the PyMLNs engine. Among the options, there is only the internal engine. If the default internal engine is used, I will add the default weight 0 before the rule as specified in the tutorial, but the inferred weight will be 0. I want to know how to solve it.

Thanks a lot!

**Comment by opcode81** [comment]
I'm sorry I never answered your question, but the "internal engine" is in fact "PyMLNs".
Not sure what you meant about the inferred weight being zero though...

**Comment by MRSHIMMER** [comment]
> I'm sorry I never answered your question, but the "internal engine" is in fact "PyMLNs". Not sure what you meant about the inferred weight being zero though...

Thank you for your reply. I must have encountered some problems that I could not understand. But later, because of the need of my project, I did not learn this knowledge anymore. Thanks again.
