### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by SND8041** [opcode81/ProbCog#9]
Hi,
I am trying to install probcog but it seems that the script make_apps.py has some issues. I have Windows 10 and JDK 10. The commands given on the "Getting Started" page on https://github.com/opcode81/ProbCog/wiki/Getting-started are followed but I am stuck on Step 4 that asks to execute "python make_apps.py". Note that I have executed the previous steps and have compiles the Java source (hopefully correct!). The error I have got when I execute python make_apps.py from 

(1) Windows command shell is:
        [C:\probcog>python make_apps.py
        ProbCog Apps Generator
                usage: make_apps [--arch=win32|win64|linux_amd64|linux_i386|macosx|macosx64] [additional 
                JVM args]
        Note: Some useful JVM args include
               -Xmx8000m   set maximum Java heap space to 8000 MB
                -ea         enable assertions
                Traceback (most recent call last):
                File "make_apps.py", line 82, in <module>
                       # check if ProbCog binaries exist
                         NameError: name 'os' is not defined]
(2) From IDLE 3.6 (Run the loaded file make_apps.py)
The error I have received is:
                ProbCog Apps Generator
                usage: make_apps [--arch=win32|win64|linux_amd64|linux_i386|macosx|macosx64] [additional 
                   JVM args]
                Note: Some useful JVM args include
    -Xmx8000m   set maximum Java heap space to 8000 MB
    -ea         enable assertions
Determining dependency classpath...
Traceback (most recent call last):
  File "C:\probcog\make_apps.py", line 111, in <module>
    dep_classpath = getDependencyClasspath()
  File "C:\probcog\make_apps.py", line 63, in getDependencyClasspath
    if "Dependencies classpath" in line:
TypeError: a bytes-like object is required, not 'str'

I am kind of a new guy in Java and Python world. I would appreciate you guys help very much.

Thanks
Syed

**Comment by opcode81** [comment]
(1) I believe there is something wrong with your Python interpreter. It reports an error in line 82, which, as it correctly prints, contains only a comment. The NameError for 'os' being reported also doesn't make sense, since 'os' imported in line 3, and there should have been an import error if it had failed.

(2) IDLE may not be using the correct Python version (2.7); could it be that it's using Python 3?

**Comment by SND8041** [comment]
I have installed Python 3.6.5. I don't know if this is the wrong one. This is what was available latest.

**Comment by SND8041** [comment]
Thank you very much. The problem was with the Python version. I removed Python 3.x and installed Python 2.7. The problem is now resolved.
Thank you once again.
Syed
